# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de5991584d54c27cc1fb9f6b5f4409b8afc135600a7b02126396b96b54b1053aa0e2d29a792a1ad7a58bbcf2a17d42bacb4dc853aa877a231f190eb776b32de

test:
  secret_key_base: c1180c507e0494cc02b14eb46192f2de8f13486afee361e14fe0a84a66e2f13a77fb1ebdcc0867781213d970128deded61c40e806d377ac8e9c2684bd90d96cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
